pages:
  google: http://www.google.com.br
  webhook: https://n8n.leandromenezes.online/webhook/e28217e6-85e6-485f-9e21-40c0e624444d
themes:
  light:
    default:
      yes: '#14A44D'
      no: '#DC4C64'
    active:
      yes: '#00ff00'
      no: '#ff0000'
  dark:
    default:
      yes: '#818181'
      no: '#161618'
    active:
      yes: '#eeeeee'
      no: '#888888'
  dracula:
    default:
      yes: '#bd93f9'
      no: '#282a36'
    active:
      yes: '#ff79c6'
      no: '#ffb86c'
config:
  direction: dynamic
  theme: default
  mode: redirect
  #mode: auth
  callmode: servercall 
  #callmode: browser
  proxy_prefix: '/confirm/'
strings:
  yes: "GO"
  no: "NO"
  open_link: "Redirecting to '{{link}}'..."
  window_title: "Confirm {{link}}"
servercall:
  regex: \"Workflow was started\"
  success_redirect: "about:blank"
  error_redirect: "https://yahoo.com"
  method: "GET"
layout:
  theme: single-button
  css: singlebutton.css
  colors: dracula