pages:
  google: http://www.google.com.br
themes:
  light:
    default:
      yes: '#14A44D'
      no: '#DC4C64'
    active:
      yes: '#00ff00'
      no: '#ff0000'
  dark:
    default:
      yes: '#818181'
      no: '#161618'
    active:
      yes: '#eeeeee'
      no: '#888888'
  dracula:
    default:
      yes: '#bd93f9'
      no: '#282a36'
    active:
      yes: '#ff79c6'
      no: '#ffb86c'
config:
  direction: dynamic
  theme: default
  mode: auth #redirect | #servercall
  proxy_prefix: '/confirm/'
#  theme: dracula
strings:
  yes: SIM
  no: NÃO
  open_link: Abrir link <br/> {{link}}?
  window_title: Confirmar abrir o link {{link}}?